/**
 * Scans public/images/ for .jpg, .jpeg, and .png files
 * and writes src/data/animals.js with Vietnamese answers from a mapping table.
 *
 * Run: node scripts/generate-animals.js
 */

const fs = require("fs");
const path = require("path");

/** Only these image types are included. */
const IMAGE_EXTENSIONS = new Set([".jpg", ".jpeg", ".png"]);

/**
 * English key = filename without extension, lowercased (example: dog.png -> "dog").
 * Add new animals here when you add new image files.
 *
 * `answer` is the main Vietnamese word you expect from the player.
 * `aliases` are other correct ways to say it.
 */
const VIETNAMESE_BY_ENGLISH = {
  // —— Examples (from the comment in your task) ——
  dog: { answer: "chó", aliases: ["chó", "con chó", "cún"] },
  cat: { answer: "mèo", aliases: ["mèo", "con mèo", "mèo con"] },

  // —— Animals in this project (expand as you like) ——
  deer: { answer: "hươu", aliases: ["hươu", "con hươu", "nai"] },
  elephant: { answer: "voi", aliases: ["voi", "con voi"] },
  giraffe: { answer: "hươu cao cổ", aliases: ["hươu cao cổ", "giraffe"] },
  horse: { answer: "ngựa", aliases: ["ngựa", "con ngựa"] },
  lion: { answer: "sư tử", aliases: ["sư tử", "con sư tử"] },
  panther: { answer: "báo", aliases: ["báo", "báo đen", "con báo"] },
  tiger: { answer: "hổ", aliases: ["hổ", "con hổ", "cọp"] },
  wolf: { answer: "sói", aliases: ["sói", "con sói"] },

  // —— Extra examples for future images (optional) ——
  bear: { answer: "gấu", aliases: ["gấu", "con gấu"] },
  bird: { answer: "chim", aliases: ["chim", "con chim"] },
  cow: { answer: "bò", aliases: ["bò", "con bò"] },
  duck: { answer: "vịt", aliases: ["vịt", "con vịt"] },
  fish: { answer: "cá", aliases: ["cá", "con cá"] },
  frog: { answer: "ếch", aliases: ["ếch", "con ếch", "cóc"] },
  monkey: { answer: "khỉ", aliases: ["khỉ", "con khỉ"] },
  mouse: { answer: "chuột", aliases: ["chuột", "con chuột"] },
  panda: { answer: "gấu trúc", aliases: ["gấu trúc", "con gấu trúc"] },
  pig: { answer: "lợn", aliases: ["lợn", "con lợn", "heo"] },
  rabbit: { answer: "thỏ", aliases: ["thỏ", "con thỏ"] },
  sheep: { answer: "cừu", aliases: ["cừu", "con cừu"] },
  snake: { answer: "rắn", aliases: ["rắn", "con rắn"] },
  zebra: { answer: "ngựa vằn", aliases: ["ngựa vằn", "con ngựa vằn"] },
};

const projectRoot = path.join(__dirname, "..");
const imagesDir = path.join(projectRoot, "public", "images");
const outFile = path.join(projectRoot, "src", "data", "animals.js");

function isImageFile(filename) {
  const ext = path.extname(filename).toLowerCase();
  return IMAGE_EXTENSIONS.has(ext);
}

function englishKeyFromFilename(filename) {
  const base = path.basename(filename, path.extname(filename));
  return base.trim().toLowerCase();
}

function buildAnimalsList() {
  if (!fs.existsSync(imagesDir)) {
    throw new Error(`Missing folder: ${imagesDir}`);
  }

  const files = fs.readdirSync(imagesDir).filter((name) => {
    if (name.startsWith(".")) return false;
    return isImageFile(name);
  });

  files.sort((a, b) => a.localeCompare(b, "en"));

  const missing = [];
  const animals = [];

  let id = 1;
  for (const file of files) {
    const englishKey = englishKeyFromFilename(file);
    const meta = VIETNAMESE_BY_ENGLISH[englishKey];

    if (!meta) {
      missing.push(file);
      continue;
    }

    const ext = path.extname(file);
    const urlPath = "/images/" + path.basename(file);

    animals.push({
      id,
      image: urlPath,
      answer: meta.answer,
      aliases: meta.aliases,
    });

    id += 1;
  }

  return { animals, missing };
}

function prettyJsStringArray(values) {
  return `[${values.map((v) => JSON.stringify(v)).join(", ")}]`;
}

function formatAnimalsJs(animals) {
  const header = `// Auto-generated by scripts/generate-animals.js\n// Do not edit by hand unless you know what you’re doing.\n\n`;

  const lines = [];
  lines.push(`const animals = [`);
  for (const a of animals) {
    lines.push(`  {`);
    lines.push(`    id: ${a.id},`);
    lines.push(`    image: ${JSON.stringify(a.image)},`);
    lines.push(`    answer: ${JSON.stringify(a.answer)},`);
    lines.push(`    aliases: ${prettyJsStringArray(a.aliases)},`);
    lines.push(`  },`);
  }
  lines.push(`];`);
  lines.push(``);
  lines.push(`export default animals;`);
  lines.push(``);

  return header + lines.join("\n");
}

function main() {
  const { animals, missing } = buildAnimalsList();

  if (missing.length > 0) {
    console.warn(
      "\n[WARN] Skipped files without a Vietnamese mapping entry. Add them to VIETNAMESE_BY_ENGLISH:\n  - " +
        missing.join("\n  - ") +
        "\n"
    );
  }

  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, formatAnimalsJs(animals), "utf8");

  console.log(`Wrote ${animals.length} animals to ${path.relative(projectRoot, outFile)}`);
}

main();
